sudo: required
dist: trusty

language: node_js
node_js: 6

os:
  - linux
      
install:
  - npm install

script:
  # - npm run travix interp . # runtime stack overflow
  - npm run travix neko .
  - npm run travix python .
  - npm run travix node .
  # - npm run travix flash .
  # - npm run travix java .
  - npm run travix cpp .
  # - npm run travix cs . # gencs stack overflow, to be investigated
  - npm run travix php .
