sudo: required
dist: trusty

language: haxe

haxe:
  - "3.4.0"
  - development
  
matrix:
  allow_failures:
    - haxe: development
    
install:
  - haxelib install travix
  - haxelib run travix install

script:
  # - haxelib run travix interp # runtime stack overflow
  - haxelib run travix neko
  - haxelib run travix python
  - haxelib run travix node
  # - haxelib run travix flash
  # - haxelib run travix java
  - haxelib run travix cpp
  # - haxelib run travix cs # gencs stack overflow, to be investigated
  - haxelib run travix php
