sudo: required
dist: trusty

jobs:
  include:
    - stage: test
      language: node_js
      node_js: 8
      os:
        - linux
        # - osx
      install:
        - npm i -g lix
        - lix download
      script:
        # - lix run travix interp # runtime stack overflow
        - lix run travix neko
        - lix run travix python
        - lix run travix node
        # - lix run travix flash
        - lix run travix java
        - lix run travix cpp
        # - lix run travix cs # gencs stack overflow, to be investigated
        - lix run travix php
        - lix run travix lua
    
    - stage: deploy
      language: haxe
      haxe: "3.4.7"
      os: linux
      script: skip
      after_success:
        - haxelib install travix
        - haxelib run travix install
        - haxelib run travix release
